export const CHANGE_THEME = "CHANGE_THEME";

export const FETCH_EXPERIENCE = "FETCH_EXPERIENCE";
export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_SKILLS = "FETCH_SKILLS";
export const FETCH_EDUCATION = "FETCH_EDUCATION";
